name: Deploy Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy_dly:
    name: Deploy to DLY
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dly
    secrets:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      
  deploy_stg:
    name: Deploy to STG
    needs: deploy_dly
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: stg
    secrets:
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
