name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      ADMIN_PASSWORD:
        required: true
      ARM_CLIENT_ID:
        required: true

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Dump Password
      run: |
        echo 
        echo Password is $ADMIN_PASSWORD
        if [[ $ADMIN_PASSWORD == *"DLY"* ]]; then
          echo "This is the DLY password!"
        elif [[ $ADMIN_PASSWORD == *"STG"* ]]; then
          echo "This is the STG password!"
        else
          echo "This is NOT the STG or DLY password!"
        fi
        echo "${{ secrets.ARM_CLIENT_ID}}" | md5sum
      env:
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}


#570a90bfbf8c7eab5dc5d4e26832d5b1
#
#fred
#
#08b622ddf7eb7c8e44cdb3bd6362f966
